apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-alert-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-alert
  template:
    metadata:
      labels:
        app: create-alert
    spec:
      containers:
        - name: create-alert
          image: naveenraj12/create-alert-service:latest
          ports:
            - containerPort: 8002
          env:
            - name: MONGO_URI
              value: mongodb://mongo-0.mongo:27017
---
apiVersion: v1
kind: Service
metadata:
  name: create-alert-service
spec:
  selector:
    app: create-alert
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002